import React from "react";
import { BrainCircuit, Check, X, Pencil, Sparkles, Filter } from "lucide-react";
import { aiItems as seed } from "../data/mockData";
import { PageHeader, Badge, StatusBadge, Button, Modal, Textarea } from "../components/common";

export default function AIReview({projectId}){
 const [items,setItems]=React.useState(seed.filter(x=>x.project===projectId)),[tab,setTab]=React.useState("Needs review"),[selected,setSelected]=React.useState(null);
 const counts={ "Auto-approved":items.filter(x=>x.status==="Auto-approved").length,"Needs review":items.filter(x=>x.status==="Needs review").length,"Unmatched":items.filter(x=>x.status==="Unmatched").length};
 const filtered=items.filter(x=>x.status===tab);
 const update=(id,status)=>setItems(items.map(x=>x.id===id?{...x,status}:x));
 const confidence=(n)=>n>90?"green":n>=60?"amber":"red";
 return <div><PageHeader title="AI review" description="AI extracts activities, dates, statuses and discipline from field reports, then matches them to schedule activities." actions={<Badge tone="teal"><BrainCircuit size={14}/> {counts["Needs review"]} items need review</Badge>}/>
 <div className="mb-5 flex gap-1 overflow-x-auto rounded-xl bg-slate-100 p-1 dark:bg-slate-800">{Object.entries(counts).map(([t,c])=><button key={t} onClick={()=>setTab(t)} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab===t?"bg-white shadow-sm dark:bg-slate-950":"text-slate-500"}`}>{t} <span className="ml-1 text-xs">{c}</span></button>)}</div>
 <div className="mb-5 grid gap-4 md:grid-cols-3"><Mini title="Extracted fields" value="98.4%" text="Activity, date and status extraction accuracy (demo metric)"/><Mini title="Semantic matching" value="91.2%" text="High-confidence matches above the approval threshold"/><Mini title="Review queue" value={counts["Needs review"]} text="Human-in-the-loop verification items"/></div>
 <div className="space-y-4">{filtered.map(item=><div key={item.id} className="surface p-5"><div className="flex flex-col gap-4 lg:flex-row"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-slate-400">{item.id} · {item.report}</span><StatusBadge status={item.status}/></div><h3 className="mt-2 text-base font-bold">Extracted report text</h3><p className="mt-2 rounded-xl bg-slate-50 p-3 text-sm leading-6 dark:bg-slate-800">{item.extracted}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border p-3"><div className="text-[11px] uppercase text-slate-400">Suggested schedule activity</div><div className="mt-1 text-sm font-semibold">{item.activity}</div></div><div className="rounded-xl border p-3"><div className="text-[11px] uppercase text-slate-400">Match explanation</div><div className="mt-1 text-sm">{item.reason}</div></div></div></div><div className="w-full lg:w-56"><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-800"><div className="text-xs muted">Similarity score</div><div className="mt-1 text-3xl font-bold">{item.similarity}%</div><div className="mt-3 text-xs muted">AI confidence</div><div className="mt-1 flex items-center justify-between"><strong>{item.confidence}%</strong><Badge tone={confidence(item.confidence)}>{item.confidence>90?"High":item.confidence>=60?"Medium":"Low"}</Badge></div></div><div className="mt-3 grid grid-cols-3 gap-2"><Button variant="secondary" className="h-9 px-2" onClick={()=>update(item.id,"Auto-approved")} title="Approve"><Check size={15}/></Button><Button variant="danger" className="h-9 px-2" onClick={()=>update(item.id,"Unmatched")} title="Reject"><X size={15}/></Button><Button variant="secondary" className="h-9 px-2" onClick={()=>setSelected(item)} title="Edit"><Pencil size={15}/></Button></div></div></div></div>)}{!filtered.length&&<div className="surface p-12 text-center"><Sparkles className="mx-auto text-teal" size={30}/><h3 className="mt-3 font-semibold">Queue is clear</h3><p className="mt-1 text-sm muted">There are no {tab.toLowerCase()} AI matches for this project.</p></div>}</div>
 <Modal open={!!selected} onClose={()=>setSelected(null)} title="Edit AI match"><div><label className="mb-2 block text-sm font-medium">Suggested activity</label><input className="input" defaultValue={selected?.activity}/><label className="mb-2 mt-4 block text-sm font-medium">Extracted text</label><Textarea defaultValue={selected?.extracted}/><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setSelected(null)}>Cancel</Button><Button onClick={()=>{if(selected)update(selected.id,"Needs review");setSelected(null)}}>Save review</Button></div></div></Modal>
 </div>
}
function Mini({title,value,text}){return <div className="surface p-4"><div className="text-xs muted">{title}</div><div className="mt-1 text-2xl font-bold">{value}</div><p className="mt-1 text-xs muted">{text}</p></div>}
