import React from "react";
import { Download, CalendarDays } from "lucide-react";
import { ResponsiveContainer, LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, AreaChart, Area } from "recharts";
import { PageHeader, ChartCard, Button, Badge } from "../components/common";
import { progressData, sCurveData, delayData, disciplineData, confidenceData } from "../data/mockData";

export default function Analytics(){
 const exportCsv=()=>{const csv="Discipline,Completion\\n"+disciplineData.map(x=>`${x.name},${x.completion}`).join("\\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="infrapulse-analytics.csv";a.click()};
 return <div><PageHeader title="Analytics" description="Delivery performance, delay patterns and AI matching quality." actions={<><Button variant="secondary"><CalendarDays size={16}/>01 Sep — 18 Sep 2026</Button><Button onClick={exportCsv}><Download size={16}/>Export CSV</Button></>}/>
 <div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Planned vs actual" subtitle="Cumulative weekly progress"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={progressData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="week"/><YAxis unit="%"/><Tooltip/><Line dataKey="planned" stroke="#64748b" strokeDasharray="5 5" strokeWidth={2}/><Line dataKey="actual" stroke="#1bb8b0" strokeWidth={3}/></LineChart></ResponsiveContainer></div></ChartCard>
 <ChartCard title="S-curve" subtitle="Cumulative planned vs actual"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={sCurveData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis unit="%"/><Tooltip/><Area dataKey="planned" stroke="#64748b" fill="#94a3b8" fillOpacity={.08}/><Area dataKey="actual" stroke="#1bb8b0" fill="#1bb8b0" fillOpacity={.1}/></AreaChart></ResponsiveContainer></div></ChartCard>
 <ChartCard title="Delay distribution" subtitle="Total variance days by discipline"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={delayData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="days" fill="#f3b33e" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></ChartCard>
 <ChartCard title="Discipline completion" subtitle="Current completion across work packages"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={disciplineData} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" unit="%"/><YAxis type="category" dataKey="name" width={80}/><Tooltip/><Bar dataKey="completion" fill="#1bb8b0" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></ChartCard>
 <ChartCard title="AI confidence score" subtitle="Review distribution"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={confidenceData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="bucket"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#3b82f6" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></ChartCard>
 <div className="surface p-5"><h3 className="section-title">Critical-path summary</h3><div className="mt-4 space-y-3">{[["Culvert C-14","8 days","High"],["Cross regulator CR-03","12 days","High"],["Pier P17 reinforcement","18 days","Critical"],["Embankment CH 3+600","3 days","Medium"]].map(x=><div key={x[0]} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><div><div className="text-sm font-semibold">{x[0]}</div><div className="text-xs muted">Schedule variance</div></div><div className="text-right"><div className="font-bold">{x[1]}</div><Badge tone={x[2]==="Critical"?"red":x[2]==="High"?"amber":"blue"}>{x[2]}</Badge></div></div>)}</div></div></div>
 </div>
}
