import React from "react";
import { Plus, Search, Eye, CloudSun } from "lucide-react";
import { reports as seed } from "../data/mockData";
import { PageHeader, Button, Modal, Input, Textarea, StatusBadge, FilterBar } from "../components/common";

export default function DailyReports({projectId}){
 const [rows,setRows]=React.useState(seed.filter(r=>r.project===projectId)),[open,setOpen]=React.useState(false),[view,setView]=React.useState(null),[q,setQ]=React.useState("");
 React.useEffect(()=>setRows(seed.filter(r=>r.project===projectId)),[projectId]);
 const [form,setForm]=React.useState({date:"2026-09-18",weather:"Clear, 30°C",workforce:"120",equipment:"20",work:"",delays:"None reported.",safety:""});
 const create=()=>{if(!form.work)return;setRows([{...form,id:`DR-${Math.floor(2000+Math.random()*8000)}`,project:projectId,submittedBy:"Hemangi Mehta",status:"Submitted"},...rows]);setOpen(false);setForm({...form,work:"",safety:""})};
 const filtered=rows.filter(r=>[r.id,r.work,r.submittedBy].join(" ").toLowerCase().includes(q.toLowerCase()));
 return <div><PageHeader title="Daily reports" description="Review field conditions, workforce, equipment and delays." actions={<Button onClick={()=>setOpen(true)}><Plus size={16}/>New daily report</Button>}/>
 <FilterBar><div className="relative flex-1 min-w-[220px]"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><Input className="pl-9" placeholder="Search reports" value={q} onChange={e=>setQ(e.target.value)}/></div><Input type="date" className="w-auto" defaultValue="2026-09-01"/><Input type="date" className="w-auto" defaultValue="2026-09-18"/></FilterBar>
 <div className="surface overflow-hidden"><div className="hidden md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500 dark:bg-slate-800/60"><tr>{["Report","Date","Weather","Workforce","Work completed","Status","Submitted by",""].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{filtered.map(r=><tr key={r.id}><td className="px-4 py-3 font-semibold">{r.id}</td><td className="px-4 py-3 text-xs">{r.date}</td><td className="px-4 py-3 text-xs">{r.weather}</td><td className="px-4 py-3">{r.workforce}</td><td className="max-w-xs px-4 py-3 text-xs"><div className="line-clamp-2">{r.work}</div></td><td className="px-4 py-3"><StatusBadge status={r.status}/></td><td className="px-4 py-3 text-xs">{r.submittedBy}</td><td className="px-4 py-3"><Button variant="ghost" className="h-8" onClick={()=>setView(r)}><Eye size={15}/>View</Button></td></tr>)}</tbody></table></div>
 <div className="divide-y md:hidden dark:divide-slate-800">{filtered.map(r=><button onClick={()=>setView(r)} key={r.id} className="block w-full p-4 text-left"><div className="flex justify-between"><span className="font-semibold">{r.id}</span><StatusBadge status={r.status}/></div><p className="mt-1 text-xs muted">{r.work}</p><div className="mt-2 text-xs muted">{r.date} · {r.workforce} workers · {r.weather}</div></button>)}</div></div>
 <Modal open={open} onClose={()=>setOpen(false)} title="New daily report" size="lg"><div className="grid gap-4 sm:grid-cols-2"><Field label="Date"><Input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field><Field label="Weather"><Input value={form.weather} onChange={e=>setForm({...form,weather:e.target.value})}/></Field><Field label="Workforce"><Input type="number" value={form.workforce} onChange={e=>setForm({...form,workforce:e.target.value})}/></Field><Field label="Equipment count"><Input type="number" value={form.equipment} onChange={e=>setForm({...form,equipment:e.target.value})}/></Field></div><div className="mt-4"><Field label="Work completed"><Textarea value={form.work} onChange={e=>setForm({...form,work:e.target.value})}/></Field></div><div className="mt-4"><Field label="Delays / constraints"><Textarea value={form.delays} onChange={e=>setForm({...form,delays:e.target.value})}/></Field></div><div className="mt-4"><Field label="Safety notes"><Textarea value={form.safety} onChange={e=>setForm({...form,safety:e.target.value})}/></Field></div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={!form.work} onClick={create}>Submit report</Button></div></Modal>
 <Modal open={!!view} onClose={()=>setView(null)} title={view?`${view.id} · Daily report`:""} size="lg">{view&&<div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Info label="Date" value={view.date}/><Info label="Weather" value={view.weather}/><Info label="Workforce" value={view.workforce}/><Info label="Equipment" value={view.equipment}/></div><Block title="Work completed" text={view.work}/><Block title="Delays" text={view.delays}/><Block title="Safety" text={view.safety}/><div className="mt-5 flex justify-between"><StatusBadge status={view.status}/><span className="text-xs muted">Submitted by {view.submittedBy}</span></div></div>}</Modal>
 </div>
}
function Field({label,children}){return <div><label className="mb-1.5 block text-sm font-medium">{label}</label>{children}</div>}
function Info({label,value}){return <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><div className="text-[11px] muted">{label}</div><div className="mt-1 text-sm font-semibold">{value}</div></div>}
function Block({title,text}){return <div className="mt-5"><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 rounded-xl bg-slate-50 p-3 text-sm leading-6 dark:bg-slate-800">{text||"No notes provided."}</p></div>}
