import React from "react";
import { Upload, Search, FileText, Image as ImageIcon, Eye, X } from "lucide-react";
import { photos as seedPhotos, documents as seedDocs } from "../data/mockData";
import { PageHeader, Button, UploadDropzone, Modal, Input, Badge, FilterBar } from "../components/common";

export default function PhotosDocuments({projectId}){
 const [photos,setPhotos]=React.useState(seedPhotos.filter(x=>x.project===projectId)),[docs,setDocs]=React.useState(seedDocs),[open,setOpen]=React.useState(false),[preview,setPreview]=React.useState(null),[q,setQ]=React.useState(""),[cat,setCat]=React.useState("All");
 const filtered=photos.filter(p=>(cat==="All"||p.category===cat)&&p.title.toLowerCase().includes(q.toLowerCase()));
 const upload=(files)=>{setOpen(false);setPhotos([{id:"PH-"+Date.now(),project:projectId,title:files[0].name,category:"Progress",date:"2026-09-18",size:"1.4 MB",src:"https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=900&q=80"},...photos])};
 return <div><PageHeader title="Photos & documents" description="Centralize field evidence, drawings, schedules and project files." actions={<Button onClick={()=>setOpen(true)}><Upload size={16}/>Upload files</Button>}/>
 <FilterBar><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><Input className="pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search photos and documents"/></div><select className="input w-auto" value={cat} onChange={e=>setCat(e.target.value)}><option>All</option><option>Progress</option><option>Safety</option><option>Structures</option></select></FilterBar>
 <div className="grid gap-5 xl:grid-cols-5"><div className="xl:col-span-3"><div className="mb-3 flex items-center justify-between"><h3 className="section-title">Site photos</h3><Badge>{filtered.length} files</Badge></div>{filtered.length?<div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{filtered.map(p=><button key={p.id} onClick={()=>setPreview(p)} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white text-left dark:border-slate-800 dark:bg-slate-900"><div className="aspect-[4/3] overflow-hidden"><img src={p.src} alt={p.title} className="h-full w-full object-cover transition group-hover:scale-105"/></div><div className="p-3"><div className="line-clamp-1 text-sm font-semibold">{p.title}</div><div className="mt-1 text-[11px] muted">{p.date} · {p.size}</div></div></button>)}</div>:<div className="surface p-10 text-center text-sm muted">No photos match your search.</div>}</div>
 <div className="xl:col-span-2"><div className="mb-3 flex items-center justify-between"><h3 className="section-title">Documents</h3><Badge>{docs.length} files</Badge></div><div className="surface divide-y divide-slate-100 overflow-hidden dark:divide-slate-800">{docs.map(d=><button key={d.id} onClick={()=>setPreview(d)} className="flex w-full items-center gap-3 p-3 text-left hover:bg-slate-50 dark:hover:bg-slate-800"><div className="rounded-xl bg-blue-50 p-2 text-blue-600 dark:bg-blue-500/10"><FileText size={18}/></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{d.name}</div><div className="mt-1 text-[11px] muted">{d.category} · {d.date} · {d.size}</div></div><Eye size={16} className="text-slate-400"/></button>)}</div></div></div>
 <Modal open={open} onClose={()=>setOpen(false)} title="Upload files"><UploadDropzone onFiles={upload} accept=".jpg,.jpeg,.png,.pdf,.xlsx,.csv,.docx" label="Drop photos or documents here"/></Modal>
 <Modal open={!!preview} onClose={()=>setPreview(null)} title={preview?.title||"Preview"} size="lg">{preview?.src?<img src={preview.src} alt={preview.title} className="max-h-[65vh] w-full rounded-xl object-contain"/>:<div className="rounded-2xl bg-slate-50 p-12 text-center dark:bg-slate-800"><FileText size={40} className="mx-auto text-slate-400"/><p className="mt-3 font-semibold">{preview?.name}</p><p className="mt-1 text-sm muted">Document preview is mocked. Connect your storage service later.</p></div>}</Modal>
 </div>
}
