import React from "react";
import { Link } from "react-router-dom";
import { Plus, Search, MapPin, CalendarDays, SlidersHorizontal } from "lucide-react";
import { projects as seed } from "../data/mockData";
import { PageHeader, Button, Input, Modal, StatusBadge, ProgressBar, Badge } from "../components/common";

export default function Projects(){
 const [rows,setRows]=React.useState(seed),[q,setQ]=React.useState(""),[status,setStatus]=React.useState("All"),[open,setOpen]=React.useState(false);
 const [form,setForm]=React.useState({name:"",client:"",location:"",start:"2026-10-01",end:"2027-12-31"});
 const filtered=rows.filter(p=>(status==="All"||p.status===status)&&[p.name,p.client,p.location].join(" ").toLowerCase().includes(q.toLowerCase()));
 const create=()=>{if(!form.name||!form.client||!form.location)return;setRows([{...form,id:`P-${Math.floor(1000+Math.random()*8999)}`,progress:0,health:100,status:"On Track",delay:0,budget:"—",manager:"Unassigned"},...rows]);setOpen(false);setForm({name:"",client:"",location:"",start:"2026-10-01",end:"2027-12-31"})};
 return <div><PageHeader title="Projects" description="Manage active construction programs and project health." actions={<Button onClick={()=>setOpen(true)}><Plus size={16}/>Create project</Button>}/>
 <div className="surface mb-5 flex flex-wrap gap-2 p-3"><div className="relative min-w-[240px] flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search projects, clients or locations" className="pl-9"/></div><select className="input w-auto" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>On Track</option><option>At Risk</option><option>Delayed</option></select><Button variant="secondary"><SlidersHorizontal size={16}/>Filters</Button></div>
 <div className="grid gap-4 lg:grid-cols-2">{filtered.map(p=><Link to={`/projects/${p.id}`} key={p.id} className="surface p-5 transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-start justify-between gap-4"><div><div className="text-base font-bold">{p.name}</div><div className="mt-1 text-xs muted">{p.id} · {p.client}</div></div><StatusBadge status={p.status}/></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><div className="flex items-center gap-2 muted"><MapPin size={14}/>{p.location}</div><div className="flex items-center gap-2 muted"><CalendarDays size={14}/>{p.start} → {p.end}</div></div><div className="mt-5 flex items-end justify-between"><div className="w-2/3"><div className="mb-1 flex justify-between text-xs"><span className="muted">Progress</span><strong>{p.progress}%</strong></div><ProgressBar value={p.progress}/></div><div className="text-right"><div className="text-xs muted">Health score</div><div className="text-lg font-bold">{p.health}<span className="text-xs text-slate-400">/100</span></div></div></div>{p.delay>0&&<Badge tone="red">+{p.delay} days delay</Badge>}</Link>)}</div>
 {filtered.length===0&&<div className="mt-5 rounded-2xl border border-dashed p-12 text-center text-sm muted">No projects match your filters.</div>}
 <Modal open={open} onClose={()=>setOpen(false)} title="Create project"><div className="space-y-4">{[["name","Project name"],["client","Client / owner"],["location","Location"]].map(([k,l])=><div key={k}><label className="mb-1.5 block text-sm font-medium">{l}</label><Input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}<div className="grid grid-cols-2 gap-3"><div><label className="mb-1.5 block text-sm font-medium">Start date</label><Input type="date" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></div><div><label className="mb-1.5 block text-sm font-medium">End date</label><Input type="date" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></div></div><div className="flex justify-end gap-2 pt-2"><Button variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={create} disabled={!form.name||!form.client||!form.location}>Create project</Button></div></div></Modal>
 </div>
}
