import React from "react";
import { CalendarRange, Filter, Upload, Eye, Search, Download } from "lucide-react";
import { activities as seed } from "../data/mockData";
import { PageHeader, Button, Modal, UploadDropzone, StatusBadge, ProgressBar, Input, FilterBar, Badge } from "../components/common";

export default function Schedule({projectId}){
 const [rows,setRows]=React.useState(seed.filter(a=>a.project===projectId)),[open,setOpen]=React.useState(false),[baseline,setBaseline]=React.useState(false),[q,setQ]=React.useState(""),[discipline,setDiscipline]=React.useState("All"),[delay,setDelay]=React.useState("All");
 React.useEffect(()=>setRows(seed.filter(a=>a.project===projectId)),[projectId]);
 const filtered=rows.filter(a=>(discipline==="All"||a.discipline===discipline)&&(delay==="All"||(delay==="Delayed"&&a.variance>0)||(delay==="On time"&&a.variance===0))&&a.name.toLowerCase().includes(q.toLowerCase()));
 const min=new Date("2026-08-01").getTime(), max=new Date("2026-11-01").getTime();
 return <div><PageHeader title="Schedule" description="Inspect activities, variance and schedule impact." actions={<><Button variant="secondary" onClick={()=>setBaseline(!baseline)}><CalendarRange size={16}/>{baseline?"Showing baseline":"Current schedule"}</Button><Button onClick={()=>setOpen(true)}><Upload size={16}/>Upload schedule</Button></>}/>
 <FilterBar><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><Input className="pl-9" placeholder="Search activities" value={q} onChange={e=>setQ(e.target.value)}/></div><select className="input w-auto" value={discipline} onChange={e=>setDiscipline(e.target.value)}><option>All</option><option>Civil</option><option>Structures</option><option>Roadworks</option><option>Electrical</option></select><select className="input w-auto" value={delay} onChange={e=>setDelay(e.target.value)}><option>All</option><option>Delayed</option><option>On time</option></select><Button variant="secondary"><Filter size={16}/>More filters</Button></FilterBar>
 <div className="surface overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-800/60"><tr>{["Activity","Discipline","Planned dates","Actual start","Status","Progress","Variance",""].map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{filtered.map(a=><tr key={a.id} className="hover:bg-slate-50/70 dark:hover:bg-slate-800/40"><td className="px-4 py-3"><div className="font-semibold">{a.name}</div><div className="text-xs muted">{a.id}</div></td><td className="px-4 py-3"><Badge>{a.discipline}</Badge></td><td className="px-4 py-3 text-xs">{a.plannedStart} → {a.plannedEnd}</td><td className="px-4 py-3 text-xs">{a.actualStart||"—"}</td><td className="px-4 py-3"><StatusBadge status={a.status}/></td><td className="min-w-32 px-4 py-3"><div className="flex items-center gap-2"><ProgressBar value={a.progress} className="flex-1"/><span className="text-xs">{a.progress}%</span></div></td><td className="px-4 py-3 font-semibold">{a.variance?`+${a.variance}d`:"0d"}</td><td className="px-4 py-3"><Button variant="ghost" className="h-8 px-2" title="View schedule impact"><Eye size={16}/></Button></td></tr>)}</tbody></table></div>
 <div className="divide-y divide-slate-100 md:hidden dark:divide-slate-800">{filtered.map(a=><div key={a.id} className="p-4"><div className="flex justify-between gap-2"><div><div className="text-sm font-semibold">{a.name}</div><div className="text-xs muted">{a.id} · {a.discipline}</div></div><StatusBadge status={a.status}/></div><div className="mt-3"><ProgressBar value={a.progress}/><div className="mt-1 flex justify-between text-xs muted"><span>{a.progress}% complete</span><span>{a.variance?`+${a.variance}d variance`:"On time"}</span></div></div></div>)}</div></div>
 <div className="mt-5 surface p-5"><div className="mb-4 flex items-center justify-between"><div><h3 className="section-title">Gantt-style timeline</h3><p className="mt-1 text-xs muted">Visualized against the current date window</p></div><Button variant="secondary"><Download size={15}/>Export</Button></div><div className="overflow-x-auto"><div className="min-w-[760px]"><div className="mb-2 ml-56 grid grid-cols-4 text-[11px] text-slate-400"><span>Aug 2026</span><span>Sep 2026</span><span>Oct 2026</span><span>Nov 2026</span></div>{filtered.map(a=>{const s=Math.max(0,(new Date(a.plannedStart)-min)/(max-min)*100), w=Math.min(100-s,(new Date(a.plannedEnd)-new Date(a.plannedStart))/(max-min)*100);return <div key={a.id} className="mb-3 flex items-center gap-3"><div className="w-52 truncate text-xs font-medium">{a.name}</div><div className="relative h-6 flex-1 rounded bg-slate-100 dark:bg-slate-800"><div className="absolute top-1/2 h-3 -translate-y-1/2 rounded bg-blue-200 dark:bg-blue-800" style={{left:`${s}%`,width:`${Math.max(w,3)}%`}}/><div className="absolute top-1/2 h-3 -translate-y-1/2 rounded bg-teal" style={{left:`${s}%`,width:`${Math.max(w*(a.progress/100),1)}%`}}/></div></div>})}</div></div></div>
 <Modal open={open} onClose={()=>setOpen(false)} title="Upload schedule" size="lg"><UploadDropzone onFiles={(files)=>{setOpen(false);alert(`${files.length} schedule file(s) uploaded to the demo queue.`)}}/><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border p-3 text-sm"><strong>Supported:</strong><p className="mt-1 text-xs muted">Primavera P6 (.xer), MS Project (.mpp), Excel (.xlsx), CSV.</p></div><div className="rounded-xl border p-3 text-sm"><strong>Demo behavior:</strong><p className="mt-1 text-xs muted">Upload is simulated locally. Backend parsing is intentionally not connected.</p></div></div></Modal>
 </div>
}
