import React from "react";
import { Mic, Camera, Send, CheckCircle2, Square } from "lucide-react";
import { activities } from "../data/mockData";
import { PageHeader, Button, Input, Textarea, ProgressBar, StatusBadge, UploadDropzone, Badge } from "../components/common";

export default function SiteProgress({projectId}){
 const acts=activities.filter(a=>a.project===projectId); const [activity,setActivity]=React.useState(acts[0]?.id||""),[pct,setPct]=React.useState(70),[qty,setQty]=React.useState(""),[notes,setNotes]=React.useState(""),[recording,setRecording]=React.useState(false),[saved,setSaved]=React.useState(false);
 const save=(e)=>{e.preventDefault();setSaved(true);setTimeout(()=>setSaved(false),2200)};
 return <div><PageHeader title="Site progress" description="Capture field progress against schedule activities."/>
 <div className="grid gap-5 lg:grid-cols-3"><form onSubmit={save} className="surface p-5 lg:col-span-2"><div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-1.5 block text-sm font-medium">Activity</label><select className="input" value={activity} onChange={e=>setActivity(e.target.value)}>{acts.map(a=><option key={a.id} value={a.id}>{a.id} · {a.name}</option>)}</select></div><div><label className="mb-1.5 block text-sm font-medium">Completion</label><div className="flex items-center gap-3"><input type="range" min="0" max="100" value={pct} onChange={e=>setPct(e.target.value)} className="w-full accent-teal"/><strong>{pct}%</strong></div></div></div><div className="mt-5"><label className="mb-1.5 block text-sm font-medium">Quantity completed</label><Input value={qty} onChange={e=>setQty(e.target.value)} placeholder="e.g. 420 m³"/></div><div className="mt-5"><label className="mb-1.5 block text-sm font-medium">Site notes</label><Textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Describe today's work, blockers, quality observations…"/></div><div className="mt-5"><label className="mb-1.5 block text-sm font-medium">Evidence</label><UploadDropzone label="Add progress photos"/><div className="mt-3 flex gap-2"><Button type="button" variant={recording?"danger":"secondary"} onClick={()=>setRecording(!recording)}>{recording?<><Square size={15}/>Stop recording</>:<><Mic size={15}/>Voice note</>}</Button>{recording&&<Badge tone="red">● Recording… 00:07</Badge>}</div></div><div className="mt-5 flex justify-end"><Button type="submit"><Send size={16}/>Submit progress</Button></div>{saved&&<div className="mt-3 flex items-center gap-2 rounded-xl bg-teal/10 p-3 text-sm text-teal-700"><CheckCircle2 size={17}/>Progress update saved to local demo state.</div>}</form>
 <div className="surface p-5"><h3 className="section-title">Assigned activities</h3><div className="mt-4 space-y-4">{acts.map(a=><div key={a.id}><div className="flex justify-between gap-2"><div><div className="text-sm font-semibold">{a.name}</div><div className="text-xs muted">{a.id}</div></div><StatusBadge status={a.status}/></div><ProgressBar value={a.progress} className="mt-2"/><div className="mt-1 text-right text-[11px] muted">{a.progress}%</div></div>)}</div></div></div>
 </div>
}
