import React from "react";
import { Plus, Mail, ShieldCheck } from "lucide-react";
import { team as seed } from "../data/mockData";
import { PageHeader, Button, Modal, Input, StatusBadge, Badge } from "../components/common";

export default function Team(){
 const [rows,setRows]=React.useState(seed),[open,setOpen]=React.useState(false),[form,setForm]=React.useState({name:"",email:"",role:"Site Engineer"});
 const invite=()=>{if(!form.name||!form.email)return;setRows([...rows,{id:Date.now(),...form,status:"Active",permissions:form.role==="Project Manager"?"Full project access":"Reports + photos"}]);setOpen(false);setForm({name:"",email:"",role:"Site Engineer"})};
 return <div><PageHeader title="Team" description="Project roles, access and collaboration." actions={<Button onClick={()=>setOpen(true)}><Plus size={16}/>Invite member</Button>}/>
 <div className="surface overflow-hidden"><div className="hidden md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500 dark:bg-slate-800/60"><tr>{["Member","Role","Status","Permissions",""].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{rows.map(m=><tr key={m.id}><td className="px-4 py-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-navy text-xs font-bold text-white dark:bg-teal dark:text-slate-950">{m.name.split(" ").map(x=>x[0]).join("")}</div><div><div className="font-semibold">{m.name}</div><div className="text-xs muted">{m.email}</div></div></div></td><td className="px-4 py-4"><Badge>{m.role}</Badge></td><td className="px-4 py-4"><StatusBadge status={m.status}/></td><td className="px-4 py-4 text-xs">{m.permissions}</td><td className="px-4 py-4"><button className="text-xs font-semibold text-teal-700">Manage</button></td></tr>)}</tbody></table></div><div className="divide-y md:hidden dark:divide-slate-800">{rows.map(m=><div key={m.id} className="p-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-navy text-xs font-bold text-white">{m.name.split(" ").map(x=>x[0]).join("")}</div><div className="flex-1"><div className="font-semibold">{m.name}</div><div className="text-xs muted">{m.email}</div></div><StatusBadge status={m.status}/></div><div className="mt-3 text-xs muted">{m.role} · {m.permissions}</div></div>)}</div></div>
 <div className="mt-5 surface p-5"><div className="flex items-center gap-2"><ShieldCheck className="text-teal" size={18}/><h3 className="section-title">Permission model</h3></div><p className="mt-2 text-sm muted">Role-based access is represented in the prototype. Connect your identity provider and authorization service later to enforce these permissions.</p></div>
 <Modal open={open} onClose={()=>setOpen(false)} title="Invite team member"><div className="space-y-4"><div><label className="mb-1.5 block text-sm font-medium">Full name</label><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="mb-1.5 block text-sm font-medium">Email</label><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><label className="mb-1.5 block text-sm font-medium">Role</label><select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>Site Engineer</option><option>Planning Engineer</option><option>Project Manager</option><option>QA/QC Engineer</option><option>Subcontractor</option></select></div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={!form.name||!form.email} onClick={invite}><Mail size={15}/>Send invite</Button></div></div></Modal>
 </div>
}
